name: ops


########################### NETWORKS
networks:
#  default:
#    driver: bridge
#  socket_proxy:
#    name: socket_proxy
  t3_proxy:
     external: true
  operations:
    name: operations
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/24

########################### SECRETS
secrets:

  # Immich
  gemini_api_key:
    file: /srv/appdata/secrets/immich/gemini_api_key
  google_maps_api_key:
    file: /srv/appdata/secrets/immich/google_maps_api_key
  immich_api_key:
    file: /srv/appdata/secrets/immich/immich_api_key
  immich_db_password:
    file: /srv/appdata/secrets/immich/immich_db_password


services:

  oxidized:
    container_name: oxidized
    image: docker.io/oxidized/oxidized:latest
    restart: unless-stopped
    # user: 0:0
    networks:
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - 8042:8888/tcp
    volumes:
      - /srv/appdata/oxidized/config:/home/oxidized/.config/oxidized
      - /srv/appdata/oxidized/ssh:/home/oxidized/.ssh
    environment:
      # Reload hosts list once per day
      CONFIG_RELOAD_INTERVAL: 86400
      # # Needed when you push to a remote git repository
      # OXIDIZED_SSH_PASSPHRASE: xxxxPassphasexxxx
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.oxidized-rtr.entrypoints=websecure"
      - "traefik.http.routers.oxidized-rtr.rule=Host(`oxidized.deercrest.info`)"
      ## Middlewares
      - "traefik.http.routers.oxidized-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.oxidized-rtr.tls=true"
      - "traefik.http.routers.oxidized-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.oxidized-rtr.service=oxidized-svc"
      - "traefik.http.services.oxidized-svc.loadbalancer.server.port=8042"


