name: immich


########################### NETWORKS
networks:
#  default:
#    driver: bridge
#  socket_proxy:
#    name: socket_proxy
  t3_proxy:
     external: true
  immich:
    name: immich
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/24

########################### SECRETS
secrets:

  # Immich
  gemini_api_key:
    file: /srv/appdata/secrets/immich/gemini_api_key
  google_maps_api_key:
    file: /srv/appdata/secrets/immich/google_maps_api_key
  immich_api_key:
    file: /srv/appdata/secrets/immich/immich_api_key
  immich_db_password:
    file: /srv/appdata/secrets/immich/immich_db_password


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.144.1
    restart: always
    depends_on:
      - redis
      - database

    environment:
      # Data Locations
      - UPLOAD_LOCATION=/pool/photos/upload
      - DB_DATA_LOCATION=/srv/appdata/immich/database
      - DOMAIN=deercrest.info
      # Database
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=/run/secrets/immich_db_password
      # Immich Server
      - IMMICH_URL="http://172.16.1.21:2283" # Your immich instace ip address and port
      - EXTERNAL_IMMICH_URL="https://photos.deercrest.info" # External address of immich
      - IMMICH_API_KEY=/run/secrets/immich_api_key
      # AP and Maps
      - GOOGLE_MAPS_API_KEY=/run/secrets/google_maps_api_key
      - GEMINI_API_KEY=/run/secrets/gemini_api_key

    ports:
      - '2283:2283'

    networks:
      - t3_proxy
      - immich
    volumes:
      - /pool/photos/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - gemini_api_key
      - google_maps_api_key
      - immich_api_key
      - immich_db_password

    healthcheck:
      disable: false

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-rtr.entrypoints=websecure"
      - "traefik.http.routers.immich-rtr.rule=Host(`photos.deercrest.info`)"
      - "traefik.http.routers.immich-rtr.tls=true"
      - "traefik.http.routers.immich-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.immich-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=2283"


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.143.1
    volumes:
      - /pool/photos/cache:/cache
    environment:
      # Data Locations
      - UPLOAD_LOCATION=/pool/photos/upload
      - DB_DATA_LOCATION=/srv/appdata/immich/database
      - DOMAIN=deercrest.info
      # Database
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=/run/secrets/immich_db_password
      # Immich Server
      - IMMICH_URL="http://172.16.1.21:2283" # Your immich instace ip address and port
      - EXTERNAL_IMMICH_URL="https://photos.deercrest.info" # External address of immich
      - IMMICH_API_KEY=/run/secrets/immich_api_key
      # AP and Maps
      - GOOGLE_MAPS_API_KEY=/run/secrets/google_maps_api_key
      - GEMINI_API_KEY=/run/secrets/gemini_api_key
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich
    secrets:
      - gemini_api_key
      - google_maps_api_key
      - immich_api_key
      - immich_db_password

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich


  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s # Requires Docker 20.10.0
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - immich
    secrets:
      - immich_db_password

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    environment:
      # Data Locations
      - UPLOAD_LOCATION=/pool/photos/upload
      - DB_DATA_LOCATION=/srv/appdata/immich/database
      - DOMAIN=deercrest.info
      # Database
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=/run/secrets/immich_db_password
      # Immich Server
      - IMMICH_URL="http://172.16.1.21:2283" # Your immich instace ip address and port
      - EXTERNAL_IMMICH_URL="https://photos.deercrest.info" # External address of immich
      - IMMICH_API_KEY=/run/secrets/immich_api_key
      # AP and Maps
      - GOOGLE_MAPS_API_KEY=/run/secrets/google_maps_api_key
      - GEMINI_API_KEY=/run/secrets/gemini_api_key
    networks:
      - t3_proxy
      - immich
    secrets:
      - gemini_api_key
      - google_maps_api_key
      - immich_api_key
      - immich_db_password 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immichtools-rtr.entrypoints=websecure"
      - "traefik.http.routers.immichtools-rtr.rule=Host(`photomagic.deercrest.info`)"
      - "traefik.http.routers.immichtools-rtr.tls=true"
      - "traefik.http.routers.immichtools-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.immichtools-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.immichtools-rtr.service=immichtools-svc"
      - "traefik.http.services.immichtools-svc.loadbalancer.server.port=3000"


