name: household

networks:
  t3_proxy:
     external: true
  household_network:
    name: household
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.88.0/24  

include:
  ########################### SERVICES
  - openwebui.yml
  - monetr.yml

