services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    # ports:
    #   - "3000:8080"
    volumes:
      - ${APPFOLDER}/open-webui:/app/backend/data
    networks:
      - t3_proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwebui.rule=Host(`openwebui.${DOMAINNAME}`)
      - traefik.http.routers.openwebui.tls=true
      - traefik.http.routers.openwebui.entrypoints=web,websecure
      - traefik.http.routers.openwebui.tls.certresolver=dns-cloudflare
      - traefik.http.routers.openwebui.middlewares=chain-authelia@file
      - traefik.http.routers.openwebui.service=openwebui
      - traefik.http.services.openwebui.loadbalancer.server.port=8080