name: Build and Push Custom n8n Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for upstream image update
        id: check-upstream
        run: |
          UPSTREAM_IMAGE="docker.n8n.io/n8nio/n8n:latest"
          LOCAL_IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/custom-n8n:latest"
          UPSTREAM_DIGEST=$(docker manifest inspect $UPSTREAM_IMAGE --format '{{ .Descriptor.Digest }}')
          LOCAL_DIGEST=$(docker manifest inspect $LOCAL_IMAGE --format '{{ .Descriptor.Digest }}' || echo "not found")
          echo "UPSTREAM_DIGEST=$UPSTREAM_DIGEST" >> $GITHUB_ENV
          echo "LOCAL_DIGEST=$LOCAL_DIGEST" >> $GITHUB_ENV

      - name: Build and push custom n8n image
        if: env.UPSTREAM_DIGEST != env.LOCAL_DIGEST
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          file: apps/n8n/dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/custom-n8n:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/custom-n8n:${{ github.sha }}